forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs/apt', :git => "https://github.com/puppetlabs/puppetlabs-apt.git"
mod 'elastic/logstash', :git => "https://github.com/zsim0n/puppet-logstash.git"
mod 'elastic/elasticsearch', :git => "https://github.com/zsim0n/puppet-elasticsearch.git"
mod 'puppetlabs/java', :git => "https://github.com/puppetlabs/puppetlabs-java.git"
mod 'zsimon/nodejs', :git => "https://github.com/zsim0n/puppet-nodejs.git"

mod "example42/puppi", :git => "https://github.com/example42/puppi.git"
mod 'example42/php', :git => "https://github.com/example42/puppet-php.git"
mod 'example42/apache', :git => "https://github.com/example42/puppet-apache.git"
mod 'example42/mysql', :git => "https://github.com/example42/puppet-mysql.git"
mod 'alup/rbenv', 		  :git => "https://github.com/alup/puppet-rbenv.git"
