forge "https://forgeapi.puppetlabs.com"


mod 'puppetlabs/stdlib', :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"
mod 'puppetlabs/concat', :git => "git://github.com/puppetlabs/puppetlabs-concat.git"
mod "example42/puppi", :git => "https://github.com/example42/puppi.git"
mod "example42/apache", :git => "https://github.com/example42/puppet-apache.git"
mod "example42/mysql", :git => "https://github.com/example42/puppet-mysql.git"
mod "example42/php", :git => "https://github.com/example42/puppet-php.git"
mod 'puppetlabs/apt',    :git => "git://github.com/puppetlabs/puppetlabs-apt.git"
mod 'puppetlabs/mongodb', :git => "git://github.com/zsim0n/puppetlabs-mongodb.git"
mod 'example42/profile', :git => "git://github.com/example42/puppet-profile.git"
mod 'alup/rbenv', 		  :git => "git://github.com/alup/puppet-rbenv.git"

# mod "example42/nginx", :git => "https://github.com/netmanagers/puppet-nginx.git"
